;=========================================================================

EXTRN Simples:Byte
EXTRN Dupla:Byte
EXTRN Duplahor:Byte
EXTRN Duplavert:Byte
EXTRN Classica:Byte
EXTRN Dotted:byte

EXTRN INITiaL_mode:byte
EXTRN textbuf:Dword
EXTRN TXT_ROWS:Byte
EXTRN TXT_colS:Byte

;==========================================================================

extrn video_INIt:NEAR
extrn gOTOXY:NEAR
extrn getXY:NEAR
extrn sETCURSOR:NEAR


EXTRN scrn_init:near
EXTRN Scrn_gotoxy:near
EXTRN Scrn_setrect:near
EXTRN Scrn_setsegment:near
EXTRN Scrn_calcoffset:near
EXTRN Scrn_color:near
EXTRN Scrn_cls:near
EXTRN Scrn_fill:near
EXTRN Scrn_printxy:near
EXTRN Scrn_print:near
EXTRN Scrn_box:near
EXTRN Scrn_Scrollup:near
EXTRN Scrn_scrollDown:near
EXTRN Scrn_getchar:near
EXTRN Scrn_getatr:near
EXTRN Scrn_setchar:near
EXTRN Scrn_setatr:near
EXTRN Scrn_Muda:near
EXTRN Scrn_Limpa:near
EXTRN Scrn_Getarea:near
EXTRN Scrn_PUtarea:near

;=========================================================================