;###########################################################
;#                                                         #
;#  Ficheiro: DEBUG.INC                                    #
;#                                                         #
;#  (c) João Pinheiro, 1998                                #
;#                                                         #
;###########################################################


;###########################################################

Extrn echo:near

EXTRN Base_number:dword
EXTRN Field_len:word
EXTRN Pad_char:byte
EXTRN Suffix:byte
EXTRN Terminator:byte

EXTRN int2Str:near
EXTRN showval:near

;###########################################################

